# Automatically generated by Net-DNS.spec.PL
%define class Net
%define subclass DNS
%define version 0.34_02
%define release 1
%define defperlver 5.6.1

# Derived values
%define real_name %{class}-%{subclass}
%define name perl-%{real_name}
%define perlver %(rpm -q perl --queryformat '%%{version}' 2> /dev/null || echo %{defperlver})

# Provide perl-specific find-{provides,requires}.
%define __find_provides %( echo -n /usr/lib/rpm/find-provides && [ -x /usr/lib/rpm/find-provides.perl ] && echo .perl )
%define __find_requires %( echo -n /usr/lib/rpm/find-requires && [ -x /usr/lib/rpm/find-requires.perl ] && echo .perl )

Summary:        Perl module %{class}::%{subclass}
Name:           %{name}
Version:        %{version}
Release:        %{release}
Group:          Development/Perl
License:        See documentation
Source:         http://www.cpan.org/modules/by-module/%{class}/%{real_name}-%{version}.tar.gz
Url:            http://search.cpan.org/search?dist=%{real_name}
Vendor:         Rob Brown <bbb@cpan.org>
BuildRequires:  perl
BuildRoot:      %{_tmppath}/%{name}-%{version}-buildroot-%(id -u -n)
Requires:       perl = %{perlver}
Provides:       %{real_name} = %{version}

%description
Perl module which implements the %{class}::%{subclass} class.

%prep
%setup -q -n %{real_name}-%{version}

%build
%{__perl} Makefile.PL
%{__make} OPTIMIZE="$RPM_OPT_FLAGS"

%install
rm -rf $RPM_BUILD_ROOT
%{makeinstall} PREFIX=$RPM_BUILD_ROOT%{_prefix}
[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress
# Clean up some files we don't want/need
rm -rf `find $RPM_BUILD_ROOT -name "perllocal.pod" -o -name ".packlist" -o -name "*.bs"`
find $RPM_BUILD_ROOT%{_prefix} -type d | tac | xargs rmdir --ign

%clean
rm -rf $RPM_BUILD_ROOT
HERE=`pwd`
cd ..
rm -rf $HERE

%files
%defattr(-,root,root)
%doc README Changes TODO contrib demo
%{_prefix}

%changelog
* Thu Nov 07 2002 Rob Brown <bbb@cpan.org>
- Version 0.30
* Fri Apr 20 2001 Rob Brown <bbb@cpan.org>
- Force man3 path to work with RH6.1 MakeMaker
* Wed Apr 18 2001 Kenneth Porter <shiva@well.com>
- (Date submitted - Sat Mar 03 2001)
- Add anti-root-clobberage to clean.
- Add contrib and demo to doc directory.
* Thu Mar 29 2001 Rob Brown <bbb@cpan.org>
- Generalize files more
* Wed Feb 07 2001 Rob Brown <bbb@cpan.org>
- Initial rpm
